apiVersion: apps/v1
kind: Deployment
metadata:
  name: sixpack-api
spec:
  template:
    metadata:
      labels:
        name: sixpack-api
    spec:
      nodeSelector:
        pool: background
      containers:
      - name: sixpack-api
        image: 'leogamas/sixpack:v0.1'
        args: ["sixpack.server:start"]
        resources:
          requests:
            memory: "128M"
            cpu: "0.2"
          limits:
            memory: "256M"
        ports:
        - containerPort: 8000
        env:
        - name: SIXPACK_CONFIG_ENABLED
          value: 'True'
        - name: SIXPACK_CONFIG_REDIS_PORT
          value: '6379'
        - name: SIXPACK_CONFIG_REDIS_HOST
          value: 'sixpack-redis-db'
        - name: SIXPACK_CONFIG_REDIS_PREFIX
          value: 'sixpack'
      imagePullSecrets:
      - name: myregistrykey
