apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sixpack-web
spec:
  template:
    metadata:
      labels:
        name: sixpack-web
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: sixpack-web
        image: 'leogamas/sixpack:v0.1'
        args: ["sixpack.web:start"]
        resources:
          requests:
            memory: "128M"
            cpu: "0.2"
          limits:
            memory: "256M"
        ports:
        - containerPort: 8000
        env:
        - name: SIXPACK_CONFIG_ENABLED
          value: 'true'
        - name: SIXPACK_CONFIG_REDIS_PORT
          value: '6379'
        - name: SIXPACK_CONFIG_REDIS_HOST
          value: 'sixpack-redis'
        - name: SIXPACK_CONFIG_REDIS_PREFIX
          value: 'sixpack'
      imagePullSecrets:
      - name: myregistrykey
